name: Build Docker Image and Deploy to App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Sign in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build & Push to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: acr3545.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t acr3545.azurecr.io/postgres-app:${{ github.sha }}
        docker push acr3545.azurecr.io/postgres-app:${{ github.sha }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'as1240958'
        images: 'acr3545.azurecr.io/postgres-app:${{ github.sha }}'

    # 5. Azure'dan Çıkış Yap
    - run: |
        az logout
